
AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'vendor/ruby/**/*'
  TargetRubyVersion: 2.5

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

NumericLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 140
  Exclude:
    - 'Gemfile'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/seeds/*'
    - 'config/routes.rb'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/application.rb'
    - 'test/test_helper.rb'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'Gemfile'
    - 'db/migrate/*'
